### ISSUE TITLE
Noisy output when compiling multiple Elm apps

### ISSUE THREAD

**Issue by neurodynamic** [phenax/esbuild-plugin-elm#11]
I've got a project with a bunch of separately compiled Elm apps, and running the build step ends up looking like this:

```
Success!     

    ElmApp1 ───> /var/folders/78/jbszfhns3ssdnsd_tkf4h_mm0000gn/T/2021111-61772-6n2ipl.le51q.js

Success!     

    ElmApp2 ───> /var/folders/78/jbszfhns3ssdnsd_tkf4h_mm0000gn/T/2021111-61772-1ezw919.3gaih.js

Success!     

    ElmApp3 ───> /var/folders/78/jbszfhns3ssdnsd_tkf4h_mm0000gn/T/2021111-61772-1g36o1k.78f9.js

Success!     

    ElmApp4 ───> /var/folders/78/jbszfhns3ssdnsd_tkf4h_mm0000gn/T/2021111-61772-1g7234x.tgwq.js

Success!     

    ElmApp5 ───> /var/folders/78/jbszfhns3ssdnsd_tkf4h_mm0000gn/T/2021111-61772-1312qs7.4127.js

Success!     

    ElmApp6 ───> /var/folders/78/jbszfhns3ssdnsd_tkf4h_mm0000gn/T/2021111-61772-1umn0ci.6ek9.js

```

If there are errors, they get buried before or in between these `Success!` notices. Can this output be silenced somehow? Or be shortened to just one line of output per app instead of four?

**Comment by phenax** [comment]
@neurodynamic, unfortunately, the output is generated from `elm make` and it doesn't allow any flags for managing verbosity of the output. I tried ignoring stdout and only showing stderr but elm outputs essential information (hints and warnings) via stdout and only the error is put in stderr so that's out of the question too.
